tls:
  certificates:
    - certFile: "/var/traefik/certs/local-cert.pem"
      keyFile: "/var/traefik/certs/local-key.pem"

http:
  routers:
    to-blog:
      rule: "Host(`blog.gabudev.cloud`) && PathPrefix(`/`)"
      # service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
      entryPoints:
        - websecure
    to-portfolio:
      rule: "Host(`gabudev.cloud`) && PathPrefix(`/`)"
      tls:
        domains:
          - main: "gabudev.cloud"
            sans:
              - "*.gabudev.cloud"
      # for prod
      # tls:
        # certResolver: staging

      service: "portfolio"
      priority: 1000
      entryPoints:
        - web
        # (optional) Permanent Redirect to HTTPS
        - websecure

  services:
    portfolio:
      loadBalancer:
        servers:
          - url: "http://gabudev.cloud"
